### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by cocampo7602** [waldekmastykarz/pnp-starterkit-setup#11] opened 2019-03-16 06:59 UTC
hi I am getting this error when I tried to install:
 - Provisioning page contents...
    - home.aspx...
      - Sections...
        - 1...DONE
        - 2...DONE
        - 3...DONE
        - 4...DONE
        - 5...DONE
      - Web parts...
        - Hero...Error: Invalid Section '1'
You can resume the script from the last good state by adding --checkPoint 270

please advise.

**Comment by waldekmastykarz** [comment] 2019-03-17 16:26
Let me see if I can reproduce it.

**Comment by waldekmastykarz** [comment] 2019-04-01 19:18
I can reproduce the issue. Sorry for the trouble. I'll try to fix it asap. Thanks for reporting 👍

**Comment by waldekmastykarz** [comment] 2019-04-07 06:05
This issue is caused by a recent change to modern pages' DOM. Two of the three affected Office 365 CLI commands have already been patched and will be released soon. The patch for the third command, which supports adding web parts, should be available in the next few days. Once it's available, provisioning the Starter Kit should working as intended again. Sorry for the trouble and stay tuned for updates.

**Comment by waldekmastykarz** [comment] 2019-04-10 18:08
All issues have been fixed. The last PR with the fix should be merged in the next release after which provisioning the starter kit using the beta version of the Office 365 CLI should be working as expected.

**Comment by waldekmastykarz** [comment] 2019-04-14 19:13
A new beta version of the Office 365 CLI with all necessary fixes has just been released. You should be able to setup the Starter Kit using this version as expected. Sorry again for the trouble and don't hesitate to reach out if there is anything else that's not working as expected.

**Closed as completed by waldekmastykarz** 2019-04-14 19:13 UTC
Labels: bug
